### ISSUE TITLE
Hiding Q&A in Space

### ISSUE THREAD

**Issue by enerAshwin** [questions-answers/community#25]
We want Q&A to be visible only to our Employees. Was able to manage this till now by hiding it from Sidebar Configuration under Space Settings. But for some reason I am finding this option anymore. Did anything change? Please let us know how can we hide it at Space level.
![image](https://user-images.githubusercontent.com/54893819/97973903-d05a5380-1dec-11eb-8320-a75d2c3d6376.png)

**Comment by Lucasus** [comment]
Hi @enerAshwin, we haven't made any application changes recently. From my initial investigation it looks like it's recently introduced bug in Confluence Cloud itself. Other applications seem to be affected as well (for example I'm not able to hide "draw.io Diagrams" in my Confluence Cloud instance):

![image](https://user-images.githubusercontent.com/731629/98006076-2087e480-1df2-11eb-8e58-4da016ff91b6.png)

**Comment by Lucasus** [comment]
In the meantime (till bug gets fixed), you can enable questions one by one for each space instead. In order to do this, you need to turn off showing questions by default (through app's global settings - see screenshot below):

![image](https://user-images.githubusercontent.com/731629/98007236-6e511c80-1df3-11eb-8fe9-adb799ebec72.png)

And then enable it in space settings configuration for spaces where questions link should be visible:

![image](https://user-images.githubusercontent.com/731629/98007381-9c366100-1df3-11eb-8bda-811d43ce47de.png)

**Comment by enerAshwin** [comment]
Thanks
This addresses our concerns.

Regards,

Ashwin
